# Generated by Django 3.1.5 on 2021-02-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210202_2111'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderLineItems',
            new_name='OrderLineItem',
        ),
    ]
