# Generated by Django 3.1.5 on 2021-02-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210209_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='strip_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
